name: starting
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #State Management
  flutter_bloc: ^8.1.5

  #powerful HTTP networking
  dio: ^5.4.3+1

  #Secure Storage
  flutter_secure_storage: ^9.2.0

  #Date Format
  intl: any

  #Flutter Toast
  fluttertoast: ^8.2.5

  #Conditional Builder
  conditional_builder_null_safety: ^0.0.6

  #Permission Handler
  permission_handler: ^11.3.1

  #Screenutil (Responsive)
  flutter_screenutil: ^5.9.1

  #Cached Network Image
  cached_network_image: ^3.3.1

  #Bottom Navigation Bar
  google_nav_bar: ^5.0.6

  #Comparing Dart Objects
  equatable: ^2.0.5

  #Service Locator
  get_it: ^7.7.0

  #Page Transition
  page_transition: ^2.1.0

  #Flutter Svg
  flutter_svg: ^2.0.10+1

  #Flutter Spinkit
  flutter_spinkit: ^5.2.1

  #Phone Number Input
  intl_phone_number_input: ^0.7.4

  #Go Router
  go_router: ^14.1.2

  #device_infomation
  package_info_plus: ^8.0.0

  #device_info_plus
  device_info_plus: ^10.1.0

  #internet_connection_checker
  internet_connection_checker: ^1.0.0+1

  #Shimmer
  shimmer: ^3.0.0

  #make request to api
  retrofit: ^4.1.0

  #Pinput
  pinput: ^4.0.0

  #Flutter Easy Debounce
  easy_debounce: ^2.0.3

  #Functional programming in Dart
  dartz: ^0.10.1

  #Badges
  badges: ^3.1.2

  #flutter_rating_bar
  flutter_rating_bar: ^4.0.1

  #flutter_easyloading
  flutter_easyloading: ^3.0.5

  #Languages
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^8.1.0
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0

flutter_gen:
  output: lib/core/utils/gen/
  line_length: 1000 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700